### ISSUE TITLE
Criar features para aumentar acurácia da entidade ORGÃO_LICITANTE e CÓDIGO_SISTEMA_DE_COMPRAS

### ISSUE THREAD

**Issue by andlq** [guilherme-mendes/timeline-contratos#186]

**Comment by Thais-ra** [comment]
![photo1651169479](https://user-images.githubusercontent.com/35047444/165839101-58180bfb-31d0-4530-b3ec-d3d42b49a644.jpeg)
![photo1651169439](https://user-images.githubusercontent.com/35047444/165839172-a7e5d91c-44fe-4810-974f-5c282c0741a0.jpeg)
![photo1651168472](https://user-images.githubusercontent.com/35047444/165839225-cd020357-f92b-469e-858a-5cc025d491e9.jpeg)
![photo1651168373](https://user-images.githubusercontent.com/35047444/165839238-2176382e-d749-4ab1-bb49-03f7fbb21378.jpeg)

**Comment by Thais-ra** [comment]
![photo1651168701](https://user-images.githubusercontent.com/35047444/165839207-03ed2fb7-7db8-4d1d-af6b-d7c1f4caef3d.jpeg)

**Comment by Thais-ra** [comment]
![photo1651169304](https://user-images.githubusercontent.com/35047444/165839344-420f4f23-1060-4268-8212-5beac6fe51ff.jpeg)
![photo1651169002](https://user-images.githubusercontent.com/35047444/165839384-98e85d56-dba4-4355-8eaf-b22320c39409.jpeg)
